apiVersion: apps/v1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample1-microservice
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: sample1-microservice
   jobs:
   - name: "scale-down"
     schedule: "30 */1 * * * *"
     targetSize: 1
   - name: "scale-up"
     schedule: "01 */1 * * * *"
     targetSize: 3
