apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample2-microservice
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: sample2-microservice
   jobs:
   - name: "scale-down"
     schedule: "30 */1 * * * *"
     targetSize: 1
     runOnce: true
   - name: "scale-up"
     schedule: "01 */1 * * * *"
     targetSize: 3
     runOnce: true
