apiVersion: "scaling.k8s.restdev.com/v1alpha1"
kind: ScheduledScaler
metadata:
  name: {{MYSCALER}}
spec:
  timeZone: America/New_York
  target:
    kind: HorizontalPodAutoscaler
    name: {{MYSERVICE}}
    apiVersion: autoscaling/v1
  steps:
  - runat: '{{MYSCHEDULESCALEUP}}'
    mode: range
    minReplicas: {{MYUPTARGET}}
    maxReplicas: {{MAXREPLICAS}}
  - runat: '{{MYSCHEDULESCALEDOWN}}'
    mode: range
    minReplicas: {{MYDOWNTARGET}}
    maxReplicas: {{MAXREPLICAS}}
---
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{MYCRONHPASCALER}}
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: {{MYSERVICE}}
   jobs:
   - name: "scale-down"
     schedule: "{{MYSCHEDULESCALEDOWN}}"
     targetSize: {{MYDOWNTARGET}}
     runOnce: {{runONCE}}
   - name: "scale-up"
     schedule: "{{MYSCHEDULESCALEUP}}"
     targetSize: {{MYUPTARGET}}
     runOnce: {{runONCE}}
