apiVersion: "scaling.k8s.restdev.com/v1alpha1"
kind: ScheduledScaler
metadata:
  name: {{MYSCALER}}
spec:
  timeZone: America/New_York
  target:
    kind: HorizontalPodAutoscaler
    name: {{MYSERVICE}}
    apiVersion: autoscaling/v1
  steps:
  - runat: '{{MYSCHEDULESCALEDOWN}}'
    mode: range
    minReplicas: {{MYDOWNTARGET}}
    maxReplicas: {{MAXREPLICAS}}