
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample1-microservice
spec:
  timeZone: America/New_York
  target:
    kind: HorizontalPodAutoscaler
    name: {{MYSERVICE}}
    apiVersion: autoscaling/v1
  steps:
  - runat: '{{MYSCHEDULESCALEUP}}'
    mode: range
    minReplicas: {{MYUPTARGET}}
    maxReplicas: {{MAXREPLICAS}}
  - runat: '{{MYSCHEDULESCALEDOWN}}'
    mode: range
    minReplicas: {{MYDOWNTARGET}}
    maxReplicas: {{MAXREPLICAS}}
